### ISSUE TITLE
convert from argb to grayscale

### ISSUE THREAD

**Issue by Andimeo** [korhner/asciimg#5]
asciimg/src/io/korhner/asciimg/image/matrix/GrayscaleMatrix.java

The blue sample extracted from rgb color seems incorrect.
Shouldn't it be "blue = color & 0xFF" instead of "blue = (color >> 8) & 0xFF"?

**Comment by korhner** [comment]
Hey, sorry for that late response, I missed this comment somehow. Nice catch, I will fix it in few days or you can send a patch as a pull request if you want. Cheers

**Comment by Andimeo** [comment]
Thanks for your response. I filed a pull request. In addition to fix the formula above, I also removed an unchecked exception and delete several unused variables.

**Comment by korhner** [comment]
Merged. Thanks!
